import { Router } from "express";
import { authenticateMiddleware } from "~/http/middleware/authenticate";
import { publicRateLimit, authenticatedRateLimit } from "~/http/middleware/rate-limit";
import { requireStoreOwner } from "~/http/middleware/permissions";
import { uploadSingleImage } from "~/http/middleware/upload";
import { createStoreController } from "./create";
import { findAllStoresController } from "./find-all";
import { findStoreByIdController } from "./find-by-id";
import { findStoreBySlugController } from "./find-by-slug";
import { getStoreStatisticsController } from "./statistics";
import { getStoreSalesAnalyticsController } from "./analytics-sales";
import { getStoreProductsAnalyticsController } from "./analytics-products";
import { getStoreCustomersAnalyticsController } from "./analytics-customers";
import { getStoreRecentActivitiesController } from "./recent-activities";
import { updateStoreController } from "./update";
import { trackStoreVisitController } from "./track-visit";
import { uploadStoreLogoController } from "./upload-logo";
import { uploadStoreBannerController } from "./upload-banner";

export const storesRoutes = Router();

storesRoutes.post("/stores", authenticatedRateLimit, authenticateMiddleware, createStoreController);
storesRoutes.get("/stores", publicRateLimit, findAllStoresController);
storesRoutes.get("/stores/:id", publicRateLimit, findStoreByIdController);
storesRoutes.get("/stores/slug/:slug", publicRateLimit, findStoreBySlugController);
storesRoutes.post("/stores/:id/visit", publicRateLimit, trackStoreVisitController);
storesRoutes.get("/stores/:id/statistics", authenticatedRateLimit, authenticateMiddleware, requireStoreOwner, getStoreStatisticsController);
storesRoutes.get("/stores/:id/activities", authenticatedRateLimit, authenticateMiddleware, requireStoreOwner, getStoreRecentActivitiesController);
storesRoutes.get("/stores/:id/analytics/sales", authenticatedRateLimit, authenticateMiddleware, requireStoreOwner, getStoreSalesAnalyticsController);
storesRoutes.get("/stores/:id/analytics/products", authenticatedRateLimit, authenticateMiddleware, requireStoreOwner, getStoreProductsAnalyticsController);
storesRoutes.get("/stores/:id/analytics/customers", authenticatedRateLimit, authenticateMiddleware, requireStoreOwner, getStoreCustomersAnalyticsController);
storesRoutes.put("/stores/:id", authenticatedRateLimit, authenticateMiddleware, requireStoreOwner, updateStoreController);
storesRoutes.post("/stores/:id/logo", authenticatedRateLimit, authenticateMiddleware, requireStoreOwner, uploadSingleImage, uploadStoreLogoController);
storesRoutes.post("/stores/:id/banner", authenticatedRateLimit, authenticateMiddleware, requireStoreOwner, uploadSingleImage, uploadStoreBannerController);
